In [59]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [60]:
from sklearn.datasets import load_iris
iris = load_iris()

In [61]:
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [62]:
iris.data[0:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [63]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [64]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [65]:
data= pd.DataFrame(data= iris.data, columns=iris.feature_names)
data['target']= iris.target

In [66]:
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [67]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
sepal length (cm)    150 non-null float64
sepal width (cm)     150 non-null float64
petal length (cm)    150 non-null float64
petal width (cm)     150 non-null float64
target               150 non-null int32
dtypes: float64(4), int32(1)
memory usage: 5.4 KB


In [68]:
data.shape

(150, 5)

In [69]:
data.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.054000           3.758667   
std             0.828066          0.433594           1.764420   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)      target  
count        150.000000  150.000000  
mean           1.198667    1.000000  
std            0.763161    0.819232  
min            0.100000    0.000000  
25%            0.300000    0.000000  
50%            1.300000    1.000000  
75%            1.800000    2.000000  
max            2.500000    2.000000

In [71]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X= sc.fit_transform(data.iloc[:,0:4])

In [72]:
Y = data['target']

In [73]:
X[0:5,:]

array([[-0.90068117,  1.03205722, -1.3412724 , -1.31297673],
       [-1.14301691, -0.1249576 , -1.3412724 , -1.31297673],
       [-1.38535265,  0.33784833, -1.39813811, -1.31297673],
       [-1.50652052,  0.10644536, -1.2844067 , -1.31297673],
       [-1.02184904,  1.26346019, -1.3412724 , -1.31297673]])

In [74]:
from sklearn.decomposition import PCA
pca1 = PCA(n_components=None)

In [75]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test= train_test_split(X, Y, test_size=0.25, random_state=0)

In [76]:
lr= LogisticRegression()
lr.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [78]:
metrics.accuracy_score(Y_test, lr.predict(X_test))

0.8157894736842105

In [79]:
metrics.confusion_matrix(Y_test, lr.predict(X_test))

array([[13,  0,  0],
       [ 0, 10,  6],
       [ 0,  1,  8]], dtype=int64)

In [83]:
print(metrics.classification_report(Y_test, lr.predict(X_test)))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        13
          1       0.91      0.62      0.74        16
          2       0.57      0.89      0.70         9

avg / total       0.86      0.82      0.82        38



In [37]:
X_train1= pca1.fit_transform(X_train)
X_test1= pca1.transform(X_test)

In [38]:
pca1.explained_variance_ratio_

array([0.72848202, 0.23423526, 0.03282692, 0.0044558 ])

In [40]:
X_train1[0:5]

array([[ 0.37343154, -0.09991741,  0.22478494,  0.02461133],
       [ 0.20590858, -1.02230589, -0.17482183, -0.01267226],
       [ 1.84762175,  0.277076  ,  0.0465275 ,  0.12872266],
       [-2.44361929, -0.17731048,  0.05953752,  0.02097339],
       [ 1.88472904,  0.54541532,  0.14884484,  0.45315617]])

In [42]:
pca2= PCA(n_components=2)
X_train2= pca2.fit_transform(X_train)
X_test2= pca2.transform(X_test)

In [43]:
pca2.explained_variance_ratio_

array([0.72848202, 0.23423526])

In [46]:
from sklearn.linear_model import LogisticRegression
classifier= LogisticRegression()

In [47]:
classifier.fit(X_train2, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [48]:
classifier.predict(X_test2)

array([2, 1, 0, 2, 0, 2, 0, 2, 2, 1, 2, 2, 1, 2, 2, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2])

In [51]:
from sklearn import metrics
metrics.accuracy_score(Y_test, classifier.predict(X_test2))

0.8421052631578947

In [52]:
metrics.confusion_matrix(Y_test, classifier.predict(X_test2))

array([[13,  0,  0],
       [ 0, 10,  6],
       [ 0,  0,  9]], dtype=int64)

In [54]:
print(metrics.classification_report(Y_test, classifier.predict(X_test2)))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        13
          1       1.00      0.62      0.77        16
          2       0.60      1.00      0.75         9

avg / total       0.91      0.84      0.84        38

